---
abstract: 'A global singleton object container'
author:
  - 'Andreas Hernitscheck <ahernit@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.005, CPAN::Meta::Converter version 2.150005'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Object-GlobalContainer
requires:
  Exporter::Autoclean: '0'
  Moose: '0'
version: '0.07'
